basePath: /api
definitions:
  model.Customer:
    properties:
      Address:
        type: string
      Birthday:
        type: string
      CarNumber:
        type: string
      Citizenship:
        type: string
      CustomerId:
        type: string
      Gender:
        type: string
      ID:
        type: string
      Name:
        type: string
      Note:
        type: string
      PhoneNumber:
        type: string
      history:
        items:
          $ref: '#/definitions/model.History'
        type: array
    type: object
  model.CustomerIdRequest:
    properties:
      CustomerId:
        type: string
    type: object
  model.CustomerRequest:
    properties:
      Address:
        type: string
      Birthday:
        type: string
      CarNumber:
        type: string
      Citizenship:
        type: string
      CustomerId:
        type: string
      Gender:
        type: string
      ID:
        type: string
      Name:
        type: string
      Note:
        type: string
      PhoneNumber:
        type: string
    type: object
  model.DateRequest:
    properties:
      Date:
        type: string
    type: object
  model.DuringRequest:
    properties:
      endDate:
        type: string
      startDate:
        type: string
    type: object
  model.History:
    properties:
      CustomerId:
        type: string
      Date:
        type: string
      HistoryId:
        type: string
      Note:
        type: string
      NumberOfPeople:
        type: integer
      Price:
        type: integer
      Room:
        type: string
    type: object
  model.HistoryIdRequest:
    properties:
      HistoryId:
        type: string
    type: object
  model.HistoryRequest:
    properties:
      CustomerId:
        type: string
      Date:
        type: string
      HistoryId:
        type: string
      Note:
        type: string
      NumberOfPeople:
        type: integer
      Price:
        type: integer
      Room:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: jjkk900925@gmail.com
    name: Jason Yang
    url: http://www.google.com
  description: CRMS_Swagger information
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://www.google.com
  title: CRMS_Swagger
  version: "1.0"
paths:
  /customer:
    delete:
      description: Delete Customer by CustomerId
      produces:
      - application/json
      responses:
        "200":
          description: 'Message": "Delete success'
          schema:
            type: string
        "500":
          description: '{"Message": err.Error()}'
          schema:
            type: string
      tags:
      - Customer
    get:
      description: Get Customer by ID
      parameters:
      - description: Customer ID
        example: L123546789
        in: query
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Customer'
        "500":
          description: '{"Message": err.Error()}'
          schema:
            type: string
      tags:
      - Customer
    post:
      consumes:
      - application/json
      description: Create a new Customer
      parameters:
      - description: Customer Information
        in: body
        name: Customer
        required: true
        schema:
          $ref: '#/definitions/model.CustomerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Customer'
        "500":
          description: '{"Message": err.Error()}'
          schema:
            type: string
      tags:
      - Customer
    put:
      consumes:
      - application/json
      description: Modify Customer
      parameters:
      - description: Customer Information
        in: body
        name: Customer
        required: true
        schema:
          $ref: '#/definitions/model.CustomerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Customer'
        "500":
          description: '{"Message": err.Error()}'
          schema:
            type: string
      tags:
      - Customer
  /customerCitizenship:
    get:
      description: Get all Customers by citizenship
      parameters:
      - description: Citizenship
        example: Taiwan
        in: query
        name: Citizenship
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Customer'
            type: array
        "500":
          description: '{"Message": err.Error()}'
          schema:
            type: string
      tags:
      - Customer
  /customerID:
    post:
      description: Get Customer by CustomerID
      parameters:
      - description: Customer id
        in: body
        name: CustomerId
        required: true
        schema:
          $ref: '#/definitions/model.CustomerIdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Customer'
            type: array
        "500":
          description: '{"Message": err.Error()}'
          schema:
            type: string
      tags:
      - Customer
  /customerList:
    get:
      consumes:
      - application/json
      description: Get all Customer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Customer'
        "500":
          description: '{"Message": "Internal Error!"}'
          schema:
            type: string
      tags:
      - Customer
  /customerName:
    get:
      description: Get Customer by CustomerName
      parameters:
      - description: Customer name
        in: query
        name: CustomerName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Message": "Delete success'
          schema:
            type: string
        "500":
          description: '{"Message": err.Error()}'
          schema:
            type: string
      tags:
      - Customer
  /customerPhone:
    get:
      description: Get Customer by CustomerPhone
      parameters:
      - description: Customer phone
        example: "0912345678"
        in: query
        name: CustomerPhone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Customer'
            type: array
        "500":
          description: '{"Message": err.Error()}'
          schema:
            type: string
      tags:
      - Customer
  /history:
    delete:
      description: Delete History by HistoryId
      parameters:
      - description: History id
        in: query
        name: HistoryId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Message": "Delete success'
          schema:
            type: string
        "500":
          description: '{"Message": err.Error()}'
          schema:
            type: string
      tags:
      - History
    post:
      description: Create a new History
      parameters:
      - description: History Information
        in: body
        name: History
        required: true
        schema:
          $ref: '#/definitions/model.HistoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.History'
        "500":
          description: '{"Message": err.Error()}'
          schema:
            type: string
      tags:
      - History
    put:
      consumes:
      - application/json
      description: Modify History
      parameters:
      - description: History Information
        in: body
        name: History
        required: true
        schema:
          $ref: '#/definitions/model.HistoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.History'
        "500":
          description: '{"Message": err.Error()}'
          schema:
            type: string
      tags:
      - History
  /historyByCustomerId:
    post:
      description: Get History By CustomerId
      parameters:
      - description: History Information
        in: body
        name: History
        required: true
        schema:
          $ref: '#/definitions/model.CustomerIdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.History'
        "500":
          description: 'Message": err.Error()'
          schema:
            type: string
      tags:
      - History
  /historyByHistoryId:
    post:
      description: Get History by HistoryId
      parameters:
      - description: History id
        in: body
        name: HistoryId
        required: true
        schema:
          $ref: '#/definitions/model.HistoryIdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.History'
        "500":
          description: '{"Message": err.Error()}'
          schema:
            type: string
      tags:
      - History
  /historyForDate:
    post:
      description: Get Histories For Date
      parameters:
      - description: History Information
        in: body
        name: History
        required: true
        schema:
          $ref: '#/definitions/model.DateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.History'
        "500":
          description: 'Message": err.Error()'
          schema:
            type: string
      tags:
      - History
  /historyForDuring:
    post:
      description: Get History For During
      parameters:
      - description: History Information
        in: body
        name: History
        required: true
        schema:
          $ref: '#/definitions/model.DuringRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.History'
        "500":
          description: '{"Message": err.Error()}'
          schema:
            type: string
      tags:
      - History
  /historyList:
    get:
      consumes:
      - application/json
      description: Get all History
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.History'
        "500":
          description: '{"Message": "Internal Error!"}'
          schema:
            type: string
      tags:
      - History
swagger: "2.0"
